import "./globals.css";
// Next
import { Poppins } from "next/font/google";
import dynamic from "next/dynamic";
import localFont from "next/font/local";
// Components
const AOS = dynamic(() => import("@/app/components/AOS"));
// Font
const poppinsFONT = Poppins({
  subsets: ["latin-ext", "latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: process.env.NEXT_PUBLIC_NAME,
  description: "Generated by BlueDuck Team (heyz dev)",
};

// Font
const CamptonBlackFont = localFont({
  src: [
    {
      path: "../../public/fonts/CamptonBlack.ttf",
      weight: "900",
      style: "normal",
    },
    {
      path: "../../public/fonts/CamptonExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
    {
      path: "../../public/fonts/CamptonBold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/CamptonSemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/CamptonMedium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/CamptonBook.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/CamptonLight.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/CamptonExtraLight.ttf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../public/fonts/CamptonThin.ttf",
      weight: "100",
      style: "normal",
    },
  ],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AOS />
      <body
        style={{
          ...CamptonBlackFont.style,
          background: `#121212`,
        }}
      >
        {children}
      </body>
    </html>
  );
}
